### ISSUE TITLE
Hard to distinguish the active search result (to nav)

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#133]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** I searched for my destination address but it came up with 10+ results (weird). Most of them are clustered around what I expected, but it was impossible to tell which / where the routing UI at the bottom of the screen was prompting me to route to was located. I expected the one in the UI to be highlighted on the map (in black).
* **What happened instead?** There were only green map pins displayed. I couldn't tell where I was choosing to route to.
* **Steps to reproduce:** Search for 273 29th St (San Francisco, California, USA).
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were searching, share with us:

* **Where were you?** AutoSmog & Oil Changers, San Francisco off Cesar Chavez St.

**Comment by nvkelso** [comment]
![screenshot_2015-11-24-15-27-59](https://cloud.githubusercontent.com/assets/853051/11389018/b8b2e490-92f0-11e5-9c5f-d086b7626e65.png)
![screenshot_2015-11-24-15-27-43](https://cloud.githubusercontent.com/assets/853051/11389020/b8dd1f9e-92f0-11e5-9b71-ca0f285a2615.png)

**Comment by mjcunningham** [comment]
@nvkelso @souperneon  is there an active state pin in the sprite sheet that we are not using in the app or does one need to be made?

**Comment by souperneon** [comment]
@mjcunningham @nvkelso the grey pin is the inactive pin and the green pin is active.

**Comment by tallytalwar** [comment]
With respect to code side of things and styling 2 things need to be done here:

* Eraser-map will have to add properties to the client data (say active search result will get a property of `state: active` and inactive search results get a property of `state:inactive`. Refer: https://github.com/tangrams/tangram-es/blob/master/osx/src/main.cpp#L83
* On the style side of things 2 draw rules with appropriate filters looking for `state` property needs to be specified.
So https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L891-L898, should look like:
```
    search:
        data: { source: search }
        draw:
            icons:
                size: [36px,46px]
                collide: false
                anchor: top
        active:
            filter: { state: active }
            draw:
                icons:
                    sprite: search-active
        inactive:
            filter: { state: inactive }
            draw:
                icons:
                    sprite: search-inactive
```
