### ISSUE TITLE
Locate me UI button not available in search result or route planning views

### ISSUE THREAD

**Issue by nvkelso** [mapzen/eraser-map#136]
* **Device name:** Samsung Galaxy S6 edge
* **Android Version:** 5.1.1
* **App build number:** master-481
* **What did you expected to happen?** When panning away from my current location, I want to easily recenter the map on my current location.
* **What happened instead?** Any time I view search results or plan a route the "locate me" UI button is hidden. It should instead always be visible (reposition to avoid being hidden by other application chrome).
* **Steps to reproduce:** Search for 273 29th St (San Francisco, California, USA).
* **Attach a screenshot** See below.
* **Attach device logs** eh.

If something happened while you were searching, share with us:

* **Where were you?** AutoSmog & Oil Changers, San Francisco off Cesar Chavez St.

**Comment by nvkelso** [comment]
![screenshot_2015-11-24-15-27-59](https://cloud.githubusercontent.com/assets/853051/11389018/b8b2e490-92f0-11e5-9c5f-d086b7626e65.png)

**Comment by mjcunningham** [comment]
cc @souperneon 

What do we think the expected behavior would be when tapping it? Would it keep the currently selected result in view and zoom out enough to show your current location? Could it get clunky w a button stack in the corner?

**Comment by souperneon** [comment]
![7](https://cloud.githubusercontent.com/assets/6125224/11505519/d0240ec4-9818-11e5-8145-8f7471cf7fbf.png)
 ^^ we should just make that happen ;)

Tapping the current location button should always do the same thing, take you to your location on the map at a set zoom level. 

@nvkelso let's leave this open till the final design is done on this screen and make sure the experience is not broken.

**Comment by mjcunningham** [comment]
:+1:

**Comment by tallytalwar** [comment]
With respect to code side of things and styling 2 things need to be done here:

* Eraser-map will have to add properties to the client data (say active search result will get a property of `state: active` and inactive search results get a property of `state:inactive`. Refer: https://github.com/tangrams/tangram-es/blob/master/osx/src/main.cpp#L83
* On the style side of things 2 draw rules with appropriate filters looking for `state` property needs to be specified.
So https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L891-L898, should look like:
```
    search:
        data: { source: search }
        draw:
            icons:
                size: [36px,46px]
                collide: false
                anchor: top
        active:
            filter: { state: active }
            draw:
                icons:
                    sprite: search-active
        inactive:
            filter: { state: inactive }
            draw:
                icons:
                    sprite: search-inactive
```
